//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFCart.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Item", Namespace="http://schemas.datacontract.org/2004/07/SFCart")]
    [System.SerializableAttribute()]
    public partial class Item : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Status", Namespace="http://schemas.datacontract.org/2004/07/SFCart")]
    [System.SerializableAttribute()]
    public partial class Status : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SFCart.ServiceReference.Status.STATE StateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Detail {
            get {
                return this.DetailField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailField, value) != true)) {
                    this.DetailField = value;
                    this.RaisePropertyChanged("Detail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SFCart.ServiceReference.Status.STATE State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="Status.STATE", Namespace="http://schemas.datacontract.org/2004/07/SFCart")]
        public enum STATE : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            OK = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Error = 1,
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.ICart")]
    public interface ICart {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICart/AddItem", ReplyAction="http://tempuri.org/ICart/AddItemResponse")]
        SFCart.ServiceReference.AddItemResponse AddItem(SFCart.ServiceReference.AddItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICart/AddItem", ReplyAction="http://tempuri.org/ICart/AddItemResponse")]
        System.Threading.Tasks.Task<SFCart.ServiceReference.AddItemResponse> AddItemAsync(SFCart.ServiceReference.AddItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICart/RemoveItem", ReplyAction="http://tempuri.org/ICart/RemoveItemResponse")]
        SFCart.ServiceReference.RemoveItemResponse RemoveItem(SFCart.ServiceReference.RemoveItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICart/RemoveItem", ReplyAction="http://tempuri.org/ICart/RemoveItemResponse")]
        System.Threading.Tasks.Task<SFCart.ServiceReference.RemoveItemResponse> RemoveItemAsync(SFCart.ServiceReference.RemoveItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICart/ClearItems", ReplyAction="http://tempuri.org/ICart/ClearItemsResponse")]
        SFCart.ServiceReference.ClearItemsResponse ClearItems(SFCart.ServiceReference.ClearItemsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICart/ClearItems", ReplyAction="http://tempuri.org/ICart/ClearItemsResponse")]
        System.Threading.Tasks.Task<SFCart.ServiceReference.ClearItemsResponse> ClearItemsAsync(SFCart.ServiceReference.ClearItemsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICart/GetCartItems", ReplyAction="http://tempuri.org/ICart/GetCartItemsResponse")]
        SFCart.ServiceReference.GetCartItemsResponse GetCartItems(SFCart.ServiceReference.GetCartItemsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICart/GetCartItems", ReplyAction="http://tempuri.org/ICart/GetCartItemsResponse")]
        System.Threading.Tasks.Task<SFCart.ServiceReference.GetCartItemsResponse> GetCartItemsAsync(SFCart.ServiceReference.GetCartItemsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICart/GetShopItems", ReplyAction="http://tempuri.org/ICart/GetShopItemsResponse")]
        SFCart.ServiceReference.GetShopItemsResponse GetShopItems(SFCart.ServiceReference.GetShopItemsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICart/GetShopItems", ReplyAction="http://tempuri.org/ICart/GetShopItemsResponse")]
        System.Threading.Tasks.Task<SFCart.ServiceReference.GetShopItemsResponse> GetShopItemsAsync(SFCart.ServiceReference.GetShopItemsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICart/GetStatus", ReplyAction="http://tempuri.org/ICart/GetStatusResponse")]
        SFCart.ServiceReference.GetStatusResponse GetStatus(SFCart.ServiceReference.GetStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICart/GetStatus", ReplyAction="http://tempuri.org/ICart/GetStatusResponse")]
        System.Threading.Tasks.Task<SFCart.ServiceReference.GetStatusResponse> GetStatusAsync(SFCart.ServiceReference.GetStatusRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddItem", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int id;
        
        public AddItemRequest() {
        }
        
        public AddItemRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddItemResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool AddItemResult;
        
        public AddItemResponse() {
        }
        
        public AddItemResponse(bool AddItemResult) {
            this.AddItemResult = AddItemResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveItem", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoveItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int id;
        
        public RemoveItemRequest() {
        }
        
        public RemoveItemRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveItemResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoveItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool RemoveItemResult;
        
        public RemoveItemResponse() {
        }
        
        public RemoveItemResponse(bool RemoveItemResult) {
            this.RemoveItemResult = RemoveItemResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ClearItems", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ClearItemsRequest {
        
        public ClearItemsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ClearItemsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ClearItemsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool ClearItemsResult;
        
        public ClearItemsResponse() {
        }
        
        public ClearItemsResponse(bool ClearItemsResult) {
            this.ClearItemsResult = ClearItemsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCartItems", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCartItemsRequest {
        
        public GetCartItemsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCartItemsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCartItemsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SFCart.ServiceReference.Item[] GetCartItemsResult;
        
        public GetCartItemsResponse() {
        }
        
        public GetCartItemsResponse(SFCart.ServiceReference.Item[] GetCartItemsResult) {
            this.GetCartItemsResult = GetCartItemsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetShopItems", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetShopItemsRequest {
        
        public GetShopItemsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetShopItemsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetShopItemsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SFCart.ServiceReference.Item[] GetShopItemsResult;
        
        public GetShopItemsResponse() {
        }
        
        public GetShopItemsResponse(SFCart.ServiceReference.Item[] GetShopItemsResult) {
            this.GetShopItemsResult = GetShopItemsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStatus", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetStatusRequest {
        
        public GetStatusRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStatusResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SFCart.ServiceReference.Status GetStatusResult;
        
        public GetStatusResponse() {
        }
        
        public GetStatusResponse(SFCart.ServiceReference.Status GetStatusResult) {
            this.GetStatusResult = GetStatusResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICartChannel : SFCart.ServiceReference.ICart, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CartClient : System.ServiceModel.ClientBase<SFCart.ServiceReference.ICart>, SFCart.ServiceReference.ICart {
        
        public CartClient() {
        }
        
        public CartClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CartClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CartClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CartClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SFCart.ServiceReference.AddItemResponse AddItem(SFCart.ServiceReference.AddItemRequest request) {
            return base.Channel.AddItem(request);
        }
        
        public System.Threading.Tasks.Task<SFCart.ServiceReference.AddItemResponse> AddItemAsync(SFCart.ServiceReference.AddItemRequest request) {
            return base.Channel.AddItemAsync(request);
        }
        
        public SFCart.ServiceReference.RemoveItemResponse RemoveItem(SFCart.ServiceReference.RemoveItemRequest request) {
            return base.Channel.RemoveItem(request);
        }
        
        public System.Threading.Tasks.Task<SFCart.ServiceReference.RemoveItemResponse> RemoveItemAsync(SFCart.ServiceReference.RemoveItemRequest request) {
            return base.Channel.RemoveItemAsync(request);
        }
        
        public SFCart.ServiceReference.ClearItemsResponse ClearItems(SFCart.ServiceReference.ClearItemsRequest request) {
            return base.Channel.ClearItems(request);
        }
        
        public System.Threading.Tasks.Task<SFCart.ServiceReference.ClearItemsResponse> ClearItemsAsync(SFCart.ServiceReference.ClearItemsRequest request) {
            return base.Channel.ClearItemsAsync(request);
        }
        
        public SFCart.ServiceReference.GetCartItemsResponse GetCartItems(SFCart.ServiceReference.GetCartItemsRequest request) {
            return base.Channel.GetCartItems(request);
        }
        
        public System.Threading.Tasks.Task<SFCart.ServiceReference.GetCartItemsResponse> GetCartItemsAsync(SFCart.ServiceReference.GetCartItemsRequest request) {
            return base.Channel.GetCartItemsAsync(request);
        }
        
        public SFCart.ServiceReference.GetShopItemsResponse GetShopItems(SFCart.ServiceReference.GetShopItemsRequest request) {
            return base.Channel.GetShopItems(request);
        }
        
        public System.Threading.Tasks.Task<SFCart.ServiceReference.GetShopItemsResponse> GetShopItemsAsync(SFCart.ServiceReference.GetShopItemsRequest request) {
            return base.Channel.GetShopItemsAsync(request);
        }
        
        public SFCart.ServiceReference.GetStatusResponse GetStatus(SFCart.ServiceReference.GetStatusRequest request) {
            return base.Channel.GetStatus(request);
        }
        
        public System.Threading.Tasks.Task<SFCart.ServiceReference.GetStatusResponse> GetStatusAsync(SFCart.ServiceReference.GetStatusRequest request) {
            return base.Channel.GetStatusAsync(request);
        }
    }
}
